/**
 * Smart Volunteer Dashboard Script
 * Implements the Matching Engine UI generation and interactive components
 */

// Dummy Data generated by the "Algorithm"
const matchedOpportunities = [
    {
        id: 101,
        title: "Teach For Future",
        ngo: "EduForAll Initative",
        icon: "fa-solid fa-graduation-cap",
        score: 98,
        time: "5 hrs/week",
        tags: [
            { name: "Teaching", matched: true },
            { name: "Communication", matched: true },
            { name: "Interactiveness", matched: true },
            { name: "Patience", matched: false },
            { name: "Empathy", matched: true }
        ]
    },
    {
        id: 102,
        title: "Design For Change",
        ngo: "Sparkshift Foundation",
        icon: "fa-solid fa-paint-brush",
        score: 85,
        time: "8 hrs total",
        tags: [
            { name: "Creativity", matched: true },
            { name: "Design", matched: false },
            { name: "Aesthetic sense", matched: true }
        ]
    },
    {
        id: 103,
        title: "Environmental Services",
        ngo: "Green Earth Network",
        icon: "fa-solid fa-tree-city",
        score: 74,
        time: "1 hour/day",
        tags: [
            { name: "Tree Planting", matched: false },
            { name: "Awareness Campaigns", matched: true },
            { name: "Waste Segregation", matched: true },
            { name: "Park Cleanups", matched: false }
        ]
    },
    {
        id: 104,
        title: "Women Empowerment",
        ngo: "Girl Power Initiative Committee",
        icon: "fa-solid fa-venus",
        score: 74,
        time: "4 hour/week",
        tags: [
            { name: "Organization", matched: false },
            { name: "Self-Help", matched: true },
            { name: "Assisting Surveys", matched: true },
            { name: "Conducting Workshops", matched: false }
        ]
    }
];

// Initialize the Smart Matches Grid dynamically
const allNGOs = [
    ...matchedOpportunities,
    {
        id: 104,
        title: "Senior Care Support",
        ngo: "Elders First Foundation",
        icon: "fa-solid fa-people-arrows",
        score: null,
        time: "3 hrs/week",
        tags: [
            { name: "Companionship", matched: false },
            { name: "Patience", matched: true },
            { name: "Eldercare", matched: false }
        ]
    },
    {
        id: 105,
        title: "Community Kitchen",
        ngo: "Food For All NGO",
        icon: "fa-solid fa-utensils",
        score: null,
        time: "2 hrs/day",
        tags: [
            { name: "Cooking", matched: false },
            { name: "Serving", matched: false },
            { name: "Teamwork", matched: true }
        ]
    }
];

let profileChartsInstantiated = false;

function showView(viewId) {
    const dashboardView = document.getElementById('dashboard-view');
    const exploreView = document.getElementById('explore-view');
    const badgesView = document.getElementById('badges-view');
    const profileView = document.getElementById('profile-view');
    const impactView = document.getElementById('impact-view');

    const navDashboard = document.getElementById('nav-dashboard');
    const navExplore = document.getElementById('nav-explore');
    const navBadges = document.getElementById('nav-badges');
    const navProfile = document.getElementById('nav-profile');
    const navImpact = document.getElementById('nav-impact');

    // reset all views
    dashboardView.style.display = 'none';
    exploreView.style.display = 'none';
    if (badgesView) badgesView.style.display = 'none';
    if (profileView) profileView.style.display = 'none';
    if (impactView) impactView.style.display = 'none';

    navDashboard.classList.remove('active');
    navExplore.classList.remove('active');
    if (navBadges) navBadges.classList.remove('active');
    if (navProfile) navProfile.classList.remove('active');
    if (navImpact) navImpact.classList.remove('active');

    if (viewId === 'explore') {
        exploreView.style.display = 'block';
        navExplore.classList.add('active');
        renderExploreNGOs(allNGOs); // Initial render showing all
    } else if (viewId === 'badges') {
        if (badgesView) badgesView.style.display = 'block';
        if (navBadges) navBadges.classList.add('active');
        renderBadges();
    } else if (viewId === 'profile') {
        if (profileView) profileView.style.display = 'block';
        if (navProfile) navProfile.classList.add('active');

        if (!profileChartsInstantiated) {
            initProfileCharts();
            profileChartsInstantiated = true;
        }
    } else if (viewId === 'impact') {
        if (impactView) impactView.style.display = 'block';
        if (navImpact) navImpact.classList.add('active');
        renderImpactReport();
    } else {
        dashboardView.style.display = 'block';
        navDashboard.classList.add('active');
    }
}

function filterNGOs() {
    const searchInput = document.getElementById('ngo-search').value.toLowerCase();
    const filteredNGOs = allNGOs.filter(opp => {
        const titleMatch = opp.title.toLowerCase().includes(searchInput);
        const ngoMatch = opp.ngo.toLowerCase().includes(searchInput);
        const tagMatch = opp.tags.some(tag => tag.name.toLowerCase().includes(searchInput));
        return titleMatch || ngoMatch || tagMatch;
    });
    renderExploreNGOs(filteredNGOs);
}

// Support for Quick Filter Suggested Chips
function setSearchQuery(query) {
    const searchInput = document.getElementById('ngo-search');
    searchInput.value = query;
    filterNGOs(); // trigger filter logic manually
}

function renderMatches() {
    const grid = document.getElementById('matches-grid');
    grid.innerHTML = ''; // Clear fallback content

    matchedOpportunities.forEach((opp, index) => {
        // Generate the matching badges based strictly on requirements
        const tagsHtml = opp.tags.map(tag =>
            `<span class="tag ${tag.matched ? 'matched' : ''}">
                ${tag.matched ? '<i class="fa-solid fa-check"></i> ' : ''}${tag.name}
            </span>`
        ).join('');

        const card = document.createElement('div');
        card.className = 'match-card';
        card.innerHTML = `
            <div class="match-score">
                <i class="fa-solid fa-bolt"></i> ${opp.score}% Match
            </div>
            
            <div class="ngo-details">
                <div class="ngo-logo">
                    <i class="${opp.icon}"></i>
                </div>
                <div>
                    <h4 style="font-size: 15px; color: var(--text-muted); font-weight: 700;">${opp.ngo}</h4>
                </div>
            </div>

            <h3 class="match-title">${opp.title}</h3>
            
            <div class="match-tags">
                ${tagsHtml}
            </div>

            <div class="match-footer">
                <span class="time-req"><i class="fa-regular fa-clock"></i> ${opp.time}</span>
                <button class="apply-btn" id="btn-${opp.id}" onclick="applyTo(${opp.id}, '${opp.title}')">
                    <span>1-Click Apply</span>
                    <i class="fa-solid fa-arrow-right"></i>
                </button>
            </div>
        `;
        grid.appendChild(card);
    });
}

function renderExploreNGOs(ngos) {
    const grid = document.getElementById('ngo-results');
    grid.innerHTML = '';

    if (ngos.length === 0) {
        grid.innerHTML = '<p style="color: var(--text-muted); padding: 20px; font-weight: 600; font-size: 16px; grid-column: 1 / -1; text-align: center;">No NGOs found matching your search criteria.</p>';
        return;
    }

    ngos.forEach((opp) => {
        const tagsHtml = opp.tags.map(tag =>
            `<span class="tag">
                ${tag.name}
            </span>`
        ).join('');

        const card = document.createElement('div');
        card.className = 'match-card';
        card.innerHTML = `
            ${opp.score ? `<div class="match-score"><i class="fa-solid fa-bolt"></i> ${opp.score}% Match</div>` : ''}
            <div class="ngo-details">
                <div class="ngo-logo">
                    <i class="${opp.icon}"></i>
                </div>
                <div>
                    <h4 style="font-size: 15px; color: var(--text-muted); font-weight: 700;">${opp.ngo}</h4>
                </div>
            </div>

            <h3 class="match-title">${opp.title}</h3>
            
            <div class="match-tags" style="margin-bottom: 24px;">
                ${tagsHtml}
            </div>

            <div class="match-footer">
                <span class="time-req"><i class="fa-regular fa-clock"></i> ${opp.time}</span>
                <button class="apply-btn" id="explore-btn-${opp.id}" onclick="applyTo(${opp.id}, '${opp.title}')" style="background: var(--primary);">
                    <span>Apply Now</span>
                    <i class="fa-solid fa-paper-plane"></i>
                </button>
            </div>
        `;
        grid.appendChild(card);
    });
}

// 1-Click Apply Functionality handling and visual feedback
function applyTo(id, title) {
    // Show premium toast notification
    showToast(`Application successfully sent for <strong>${title}</strong>! 🎉`);

    // Animate button into a disabled "Applied" state
    const targetBtn1 = document.getElementById(`btn-${id}`);
    const targetBtn2 = document.getElementById(`explore-btn-${id}`);

    [targetBtn1, targetBtn2].forEach(targetBtn => {
        if (targetBtn) {
            targetBtn.innerHTML = `<span>Applied Successfully</span> <i class="fa-solid fa-check-double"></i>`;
            targetBtn.style.background = 'var(--success)';
            targetBtn.style.color = '#fff';
            targetBtn.disabled = true;
            targetBtn.style.cursor = 'not-allowed';
            targetBtn.style.transform = 'none';
            targetBtn.style.boxShadow = 'none';
        }
    });
}

// Custom Toast notification generator
function showToast(htmlMessage) {
    const container = document.getElementById('toast-container');
    const toast = document.createElement('div');
    toast.className = 'toast';
    toast.innerHTML = `<i class="fa-solid fa-circle-check toast-icon"></i> <span>${htmlMessage}</span>`;

    container.appendChild(toast);

    // Auto remove after 4 seconds with fade out animation
    setTimeout(() => {
        toast.style.opacity = '0';
        toast.style.transform = 'translateX(100px)';
        toast.style.transition = 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)';
        setTimeout(() => toast.remove(), 400);
    }, 4000);
}

// Initialize the Data Visualization (Impact Chart)
function initChart() {
    const canvas = document.getElementById('impactChart');
    if (!canvas) return;

    const ctx = canvas.getContext('2d');

    // Create gradient fill for the line chart
    const gradient = ctx.createLinearGradient(0, 0, 0, 300);
    gradient.addColorStop(0, 'rgba(99, 102, 241, 0.2)'); // var(--primary) transparent
    gradient.addColorStop(1, 'rgba(99, 102, 241, 0)');

    new Chart(ctx, {
        type: 'line',
        data: {
            labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
            datasets: [{
                label: 'Volunteer Hours (Monthly)',
                data: [12, 18, 15, 25, 22, 32],
                borderColor: '#6366f1', // var(--primary)
                backgroundColor: gradient,
                borderWidth: 4,
                tension: 0.4, // Smooth curves
                pointBackgroundColor: '#fff',
                pointBorderColor: '#6366f1',
                pointBorderWidth: 3,
                pointRadius: 6,
                pointHoverRadius: 8,
                fill: true
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: { display: false },
                tooltip: {
                    backgroundColor: '#0f172a',
                    padding: 12,
                    titleFont: { family: "'Plus Jakarta Sans', sans-serif", size: 14 },
                    bodyFont: { family: "'Plus Jakarta Sans', sans-serif", size: 14, weight: 'bold' },
                    displayColors: false,
                    cornerRadius: 8
                }
            },
            scales: {
                x: {
                    grid: { display: false },
                    ticks: { font: { family: "'Plus Jakarta Sans'" } }
                },
                y: {
                    grid: { borderDash: [6, 6], color: '#e2e8f0' },
                    beginAtZero: true,
                    ticks: { font: { family: "'Plus Jakarta Sans'" } }
                }
            }
        }
    });
}

// On document load
document.addEventListener('DOMContentLoaded', () => {
    // Render the dynamic HTML
    renderMatches();
    // Start Chart.js
    initChart();
    // Hydrate User Data
    hydrateUserData();
});

// --- USER DATA HYDRATION ---
function hydrateUserData() {
    const userDataStr = localStorage.getItem('smartVol_user');
    if (userDataStr) {
        const user = JSON.parse(userDataStr);

        // 1. Sidebar Avatar Name
        const sidebarName = document.querySelector('.sidebar-footer .user-text h4');
        if (sidebarName) sidebarName.textContent = user.name;

        // 2. Greeting Header
        const greetingHeader = document.querySelector('.greeting h1');
        if (greetingHeader) {
            // Extract first name for the greeting
            const firstName = user.name.split(' ')[0];
            greetingHeader.innerHTML = `Welcome back, ${firstName}! 👋`;
        }

        // 3. Profile View Data Binding
        const profileName = document.querySelector('#profile-view .profile-header h2');
        if (profileName) profileName.textContent = user.name;

        // 4. Detailed Profile View items
        const profileDetails = document.querySelectorAll('#profile-view .detail-item p');
        // Based on our HTML structure: 0=Email, 1=Location, 2=Contact
        if (profileDetails.length >= 3) {
            profileDetails[0].textContent = user.email;
            profileDetails[1].textContent = user.location;
            profileDetails[2].textContent = user.phone;
        }
    }
}

// --- IMPACT REPORT FUNCTIONALITY ---
const ngoActivityLog = [
    { ngo: "EduForAll Initiative", task: "Teaching Mathematics", hours: 4, date: "Oct 24, 2024", impact: "Helped 15 students" },
    { ngo: "Sparkshift Foundation", task: "Designing Flyers", hours: 8, date: "Nov 02, 2024", impact: "Reached 500+ locals" },
    { ngo: "Green Earth Network", task: "Tree Planting Setup", hours: 6, date: "Dec 12, 2024", impact: "Planted 50 Trees" },
    { ngo: "Girl Power Initiative", task: "Workshop Setup", hours: 3, date: "Jan 05, 2025", impact: "Assisted 30 women" }
];

let impactChartsInstantiated = false;

function renderImpactReport() {
    renderActivityFeed();

    // Only init charts once to avoid canvas redrawing errors
    if (!impactChartsInstantiated) {
        initNGOChart();
        initSkillRadarChart();
        impactChartsInstantiated = true;
    }
}

function renderActivityFeed() {
    const feed = document.querySelector('.activity-feed');
    if (!feed) return;
    feed.innerHTML = '';

    ngoActivityLog.forEach((log) => {
        const item = document.createElement('div');
        item.className = 'activity-item';
        item.innerHTML = `
            <div class="activity-icon"><i class="fa-solid fa-check"></i></div>
            <div class="activity-content">
                <div style="display: flex; justify-content: space-between; align-items: flex-start;">
                    <div>
                        <h4>${log.task}</h4>
                        <p>${log.ngo}</p>
                    </div>
                </div>
                <div class="activity-meta">
                    <span><i class="fa-regular fa-clock"></i> ${log.hours} Hours Logged</span>
                    <span style="color: var(--success);"><i class="fa-solid fa-chart-line"></i> ${log.impact}</span>
                </div>
            </div>
        `;
        feed.appendChild(item);
    });
}

function initNGOChart() {
    const canvas = document.getElementById('ngoDistributionChart');
    if (!canvas) return;

    new Chart(canvas.getContext('2d'), {
        type: 'doughnut',
        data: {
            labels: ['Education', 'Environment', 'Women Auth', 'Healthcare', 'Relief'],
            datasets: [{
                data: [45, 25, 15, 10, 5],
                backgroundColor: ['#6366f1', '#10b981', '#f59e0b', '#ec4899', '#8b5cf6'],
                borderWidth: 0,
                hoverOffset: 4
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            cutout: '75%',
            plugins: {
                legend: { position: 'right', labels: { font: { family: "'Plus Jakarta Sans'" }, color: '#64748b' } }
            }
        }
    });
}

function initSkillRadarChart() {
    const canvas = document.getElementById('skillsRadarChart');
    if (!canvas) return;

    new Chart(canvas.getContext('2d'), {
        type: 'radar',
        data: {
            labels: ['Teaching', 'Design', 'Communication', 'Organization', 'Leadership', 'Empathy'],
            datasets: [{
                label: 'Skill Match Usage',
                data: [90, 60, 85, 50, 75, 95],
                backgroundColor: 'rgba(99, 102, 241, 0.2)',
                borderColor: '#6366f1',
                pointBackgroundColor: '#6366f1',
                pointHoverBackgroundColor: '#fff',
                pointHoverBorderColor: '#6366f1'
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            scales: {
                r: {
                    angleLines: { color: '#e2e8f0' },
                    grid: { color: '#e2e8f0' },
                    pointLabels: { font: { family: "'Plus Jakarta Sans'", size: 12 }, color: '#475569' },
                    ticks: { display: false }
                }
            },
            plugins: { legend: { display: false } }
        }
    });
}

// --- PROFILE GRAPHS FUNCTIONALITY ---

function initProfileCharts() {
    const hoursCanvas = document.getElementById('profileHoursChart');
    const scoreCanvas = document.getElementById('profileScoreChart');
    if (!hoursCanvas || !scoreCanvas) return;

    // Monthly Hours Bar Chart
    new Chart(hoursCanvas.getContext('2d'), {
        type: 'bar',
        data: {
            labels: ['Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
            datasets: [{
                label: 'Hours Logged',
                data: [14, 22, 18, 26, 30, 24],
                backgroundColor: '#6366f1',
                borderRadius: 4
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: { legend: { display: false } },
            scales: {
                x: { grid: { display: false }, ticks: { font: { family: "'Plus Jakarta Sans'" } } },
                y: { grid: { borderDash: [4, 4], color: '#e2e8f0' }, ticks: { font: { family: "'Plus Jakarta Sans'" } } }
            }
        }
    });

    // Impact Score Line Chart
    const ctx = scoreCanvas.getContext('2d');
    const gradient = ctx.createLinearGradient(0, 0, 0, 250);
    gradient.addColorStop(0, 'rgba(16, 185, 129, 0.2)');
    gradient.addColorStop(1, 'rgba(16, 185, 129, 0)');

    new Chart(ctx, {
        type: 'line',
        data: {
            labels: ['Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
            datasets: [{
                label: 'Impact Score',
                data: [72, 78, 85, 82, 91, 95],
                borderColor: '#10b981', // var(--success)
                backgroundColor: gradient,
                borderWidth: 3,
                tension: 0.3,
                fill: true,
                pointBackgroundColor: '#fff',
                pointBorderColor: '#10b981',
                pointRadius: 4
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: { legend: { display: false } },
            scales: {
                x: { grid: { display: false }, ticks: { font: { family: "'Plus Jakarta Sans'" } } },
                y: { min: 50, max: 100, grid: { borderDash: [4, 4], color: '#e2e8f0' }, ticks: { font: { family: "'Plus Jakarta Sans'" } } }
            }
        }
    });
}
